apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: weishiuan/client
          env:
            - name: STRIPE_SECRET_KEY
              value: 'sk_test_51QDmg000hRbHMI0GqQm12CEotOBxxHC9xQxr1GqnmPaRpw5ujom8rmKRy0u1EIDe3Tsdhc57edG5e0fjzbaqV2qu00rTIeRh8f'
            - name: STRIPE_PUBLIC_KEY
              value: 'pk_test_51QDmg000hRbHMI0G9BkUuSvbjxhhvlZZ3cfcSoRHt4kMrqS5dvdSY9VPeJpLOxomEFEg0BWFlci8XyEyrWWVSmg800E8u4vZrv'
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
